# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradewave.Entity'),
            preserve_default=False,
        ),
    ]
