# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tradewave.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('date_last_transacted', models.DateTimeField(auto_now=True, verbose_name=b'date last transacted')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('series', models.PositiveSmallIntegerField()),
                ('amount_issued', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_redeemed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit_rating', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'date issued')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name=b'date last updated')),
                ('date_expire', models.DateTimeField(default=tradewave.models.one_year_from_now, verbose_name=b'date to expire')),
                ('date_last_transacted', models.DateTimeField(verbose_name=b'date of last transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CreditMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Account')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Credit')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('can_issue', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=100.0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name=b'date last updated')),
            ],
            options={
                'permissions': (('entity_admin', 'Admin of entity'), ('entity_manager', 'Manager of entity'), ('entity_employee', 'Employee of entity')),
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradewaveUser',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('pin', models.PositiveSmallIntegerField()),
                ('qr_image', models.ImageField(upload_to=b'qr')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'date joined')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name=b'date last updated')),
            ],
            options={
                'permissions': (('credit_transact', 'Is allowed to make transactions'),),
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('redeemed', models.BooleanField(default=False)),
                ('date_transacted', models.DateTimeField(auto_now_add=True, verbose_name=b'transaction timestamp')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Credit')),
                ('transact_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to='tradewave.Account')),
                ('transact_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='tradewave.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name=b'date last updated')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.City')),
            ],
        ),
        migrations.CreateModel(
            name='VenueMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tradewave.Entity')),
            ],
            bases=('tradewave.entity',),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tradewave.Entity')),
                ('has_csa', models.BooleanField(default=False)),
                ('max_credits_to_issue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Industry')),
            ],
            bases=('tradewave.entity',),
        ),
        migrations.AddField(
            model_name='venuemap',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Entity'),
        ),
        migrations.AddField(
            model_name='venuemap',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Venue'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Venue'),
        ),
        migrations.AddField(
            model_name='tradewaveuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', through='tradewave.Relationship', to='tradewave.Entity'),
        ),
        migrations.AddField(
            model_name='tradewaveuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradewaveuser',
            name='user_entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Entity'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Entity'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.TradewaveUser'),
        ),
        migrations.AddField(
            model_name='entity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Account'),
        ),
        migrations.AddField(
            model_name='entity',
            name='venues',
            field=models.ManyToManyField(through='tradewave.VenueMap', to='tradewave.Venue'),
        ),
        migrations.AddField(
            model_name='credit',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Entity'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('name', 'state', 'country')]),
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ManyToManyField(through='tradewave.CreditMap', to='tradewave.Credit'),
        ),
        migrations.AddField(
            model_name='tradewaveuser',
            name='marketplaces',
            field=models.ManyToManyField(blank=True, related_name='users', to='tradewave.Marketplace'),
        ),
        migrations.AddField(
            model_name='tradewaveuser',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='users', to='tradewave.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([('user', 'entity', 'relationship')]),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.City'),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='vendors',
            field=models.ManyToManyField(through='tradewave.Affiliation', to='tradewave.Vendor'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Marketplace'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Vendor'),
        ),
    ]
