# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0002_auto_20160215_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='amount_redeemed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_rating',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_last_transacted',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'date of last transaction'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='series',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='credit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tradewaveuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
