# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0005_remove_entity_user_tradewave'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProductMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditproductmap',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Credit'),
        ),
        migrations.AddField(
            model_name='creditproductmap',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Product'),
        ),
        migrations.AddField(
            model_name='credit',
            name='products',
            field=models.ManyToManyField(through='tradewave.CreditProductMap', to='tradewave.Product'),
        ),
    ]
