# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0008_auto_20160225_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='products',
            field=models.ManyToManyField(blank=True, through='tradewave.CreditProductMap', to='tradewave.Product'),
        ),
    ]
