# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0009_auto_20160225_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradewaveuser',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='tradewaveuser',
            name='qr_string',
            field=models.CharField(default='qr_string', max_length=1024),
            preserve_default=False,
        ),
    ]
