# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tradewave.models

import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0011_auto_20160228_0833'),
    ]

    operations = [
        migrations.DeleteModel(
            'transactionlog'
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('redeemed', models.BooleanField(default=False)),
                ('date_transacted', models.DateTimeField(auto_now_add=True, verbose_name=b'transaction timestamp')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Credit')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradewave.Venue')),
                ('transact_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to='tradewave.Account')),
                ('transact_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='tradewave.Account')),
            ],
        ),
    ]
