# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0013_auto_20160705_0822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VenueMap',
            new_name='EntityVenues',
        ),
        migrations.RenameModel(
            old_name='Affiliation',
            new_name='MarketplaceVendors',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='industry',
        ),
        migrations.AddField(
            model_name='vendor',
            name='products',
            field=models.ManyToManyField(blank=True, to='tradewave.Product'),
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
