# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tradewave.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0014_auto_20161204_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('date_expires', models.DateTimeField(default=tradewave.models.one_week_from_now, verbose_name=b'date invite token expires')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradewave.Entity')),
            ],
        ),
    ]
