# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tradewave.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0015_invites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('token_type', models.CharField(max_length=20)),
                ('date_expires', models.DateTimeField(default=tradewave.models.one_week_from_now, verbose_name=b'date invite token expires')),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradewave.Marketplace')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradewave.Vendor')),
            ],
        ),
        migrations.RemoveField(
            model_name='invites',
            name='entity',
        ),
        migrations.DeleteModel(
            name='Invites',
        ),
    ]
