# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradewave', '0017_auto_20170129_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'permissions': (('entity_marketplace', 'Must be a marketplace entity'), ('full_access', 'Marketplace has full access to all features'))},
        ),
        migrations.AlterModelOptions(
            name='tradewaveuser',
            options={'permissions': (('can_transact', 'Is allowed to make transactions'),)},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': (('entity_vendor', 'Must be a vendor entity'),)},
        ),
    ]
